### ISSUE TITLE
FE/<RecoilRoot> 최상단 태그 내에서 사용... 에러 

### ISSUE THREAD

**Issue by rmaomina** [codestates-seb/seb40_main_023#130]
## 이슈 내용
<RecoilRoot> 최상단 태그 내에서 사용... 에러 

## 기능 구현 마감일 
.

## 에러가 난 경위
무한 스크롤과 복망고 페이지네이션 작업한 내용을 PR하기 전에 pull merge했습니다. 
충돌 해결하고 실행해보니 다음과 같은 에러가 났습니다.
아마 최상단 루트에서 컴포넌트들을 감싸지 않았다고 나오는데, _app에 잘 적용해 주신 것까지 확인했습니다. 
에러가 나는 컴포넌트는 접속시 마주하는 첫 컴포넌트.. Home, Sidebar..

<img width="737" alt="image" src="https://user-images.githubusercontent.com/36831218/205142408-3f8ef39f-9974-4b3a-aaff-b0b61f13b434.png">

-------------------------
## 확인 사항
- 브랜치명: feat/#<이슈번호><내용> 
- **1review required to merge into dev**

## **커밋 규칙**

```bash
# 모든 레이블은 소문자로 작성
git commit -m "feat/commit messages"
```

- `feat` : 새로운 기능 추가, 기존의 기능을 요구 사항에 맞추어 수정
- `fix` : 기능에 대한 버그 수정
- `build` : 빌드 관련 수정
- `chore` : 패키지 매니저 수정, 그 외 기타 수정 ex) .gitignore
- `docs` : 문서(주석) 수정
- `style` : 코드 스타일, 포맷팅에 대한 수정
- `refactor` : 기능의 변화가 아닌 코드 리팩터링 ex) 변수 이름 변경
- `release` : 버전 릴리즈
- `merge` : 병합

**Comment by Exist95** [comment]
이슈 확인했습니다!

**Comment by hongdahee** [comment]
확인했습니다
